settings:
  APP_DISPLAY_NAME: SubVerse
  PRODUCTION_APP_NAME: SubVerse
  APP_GROUP_IDENTIFIER: group.SubVerse
  BASE_BUNDLE_IDENTIFIER: io.element.elementx
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
 
